/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedContentTypesIndexRouteImport } from './routes/_authenticated/content-types/index'
import { Route as AuthenticatedContentItemsIndexRouteImport } from './routes/_authenticated/content-items/index'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated/users/new'
import { Route as AuthenticatedRolesNewRouteImport } from './routes/_authenticated/roles/new'
import { Route as AuthenticatedUsersIdIndexRouteImport } from './routes/_authenticated/users/$id/index'
import { Route as AuthenticatedRolesIdIndexRouteImport } from './routes/_authenticated/roles/$id/index'
import { Route as AuthenticatedContentTypesNewIndexRouteImport } from './routes/_authenticated/content-types/new/index'
import { Route as AuthenticatedContentTypesNameIndexRouteImport } from './routes/_authenticated/content-types/$name/index'
import { Route as AuthenticatedContentItemsIdIndexRouteImport } from './routes/_authenticated/content-items/$id/index'
import { Route as AuthenticatedUsersIdEditRouteImport } from './routes/_authenticated/users/$id/edit'
import { Route as AuthenticatedContentTypesNameEditRouteImport } from './routes/_authenticated/content-types/$name/edit'
import { Route as AuthenticatedContentItemsIdEditRouteImport } from './routes/_authenticated/content-items/$id/edit'
import { Route as AuthenticatedContentTypesNameItemsIndexRouteImport } from './routes/_authenticated/content-types/$name/items/index'
import { Route as AuthenticatedContentTypesNameItemsNewRouteImport } from './routes/_authenticated/content-types/$name/items/new'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentTypesIndexRoute =
  AuthenticatedContentTypesIndexRouteImport.update({
    id: '/content-types/',
    path: '/content-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentItemsIndexRoute =
  AuthenticatedContentItemsIndexRouteImport.update({
    id: '/content-items/',
    path: '/content-items/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesNewRoute = AuthenticatedRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIdIndexRoute =
  AuthenticatedUsersIdIndexRouteImport.update({
    id: '/users/$id/',
    path: '/users/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesIdIndexRoute =
  AuthenticatedRolesIdIndexRouteImport.update({
    id: '/roles/$id/',
    path: '/roles/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentTypesNewIndexRoute =
  AuthenticatedContentTypesNewIndexRouteImport.update({
    id: '/content-types/new/',
    path: '/content-types/new/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentTypesNameIndexRoute =
  AuthenticatedContentTypesNameIndexRouteImport.update({
    id: '/content-types/$name/',
    path: '/content-types/$name/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentItemsIdIndexRoute =
  AuthenticatedContentItemsIdIndexRouteImport.update({
    id: '/content-items/$id/',
    path: '/content-items/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIdEditRoute =
  AuthenticatedUsersIdEditRouteImport.update({
    id: '/users/$id/edit',
    path: '/users/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentTypesNameEditRoute =
  AuthenticatedContentTypesNameEditRouteImport.update({
    id: '/content-types/$name/edit',
    path: '/content-types/$name/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentItemsIdEditRoute =
  AuthenticatedContentItemsIdEditRouteImport.update({
    id: '/content-items/$id/edit',
    path: '/content-items/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentTypesNameItemsIndexRoute =
  AuthenticatedContentTypesNameItemsIndexRouteImport.update({
    id: '/content-types/$name/items/',
    path: '/content-types/$name/items/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContentTypesNameItemsNewRoute =
  AuthenticatedContentTypesNameItemsNewRouteImport.update({
    id: '/content-types/$name/items/new',
    path: '/content-types/$name/items/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/content-items': typeof AuthenticatedContentItemsIndexRoute
  '/content-types': typeof AuthenticatedContentTypesIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/content-items/$id/edit': typeof AuthenticatedContentItemsIdEditRoute
  '/content-types/$name/edit': typeof AuthenticatedContentTypesNameEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/content-items/$id': typeof AuthenticatedContentItemsIdIndexRoute
  '/content-types/$name': typeof AuthenticatedContentTypesNameIndexRoute
  '/content-types/new': typeof AuthenticatedContentTypesNewIndexRoute
  '/roles/$id': typeof AuthenticatedRolesIdIndexRoute
  '/users/$id': typeof AuthenticatedUsersIdIndexRoute
  '/content-types/$name/items/new': typeof AuthenticatedContentTypesNameItemsNewRoute
  '/content-types/$name/items': typeof AuthenticatedContentTypesNameItemsIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/content-items': typeof AuthenticatedContentItemsIndexRoute
  '/content-types': typeof AuthenticatedContentTypesIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/content-items/$id/edit': typeof AuthenticatedContentItemsIdEditRoute
  '/content-types/$name/edit': typeof AuthenticatedContentTypesNameEditRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/content-items/$id': typeof AuthenticatedContentItemsIdIndexRoute
  '/content-types/$name': typeof AuthenticatedContentTypesNameIndexRoute
  '/content-types/new': typeof AuthenticatedContentTypesNewIndexRoute
  '/roles/$id': typeof AuthenticatedRolesIdIndexRoute
  '/users/$id': typeof AuthenticatedUsersIdIndexRoute
  '/content-types/$name/items/new': typeof AuthenticatedContentTypesNameItemsNewRoute
  '/content-types/$name/items': typeof AuthenticatedContentTypesNameItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/roles/new': typeof AuthenticatedRolesNewRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/content-items/': typeof AuthenticatedContentItemsIndexRoute
  '/_authenticated/content-types/': typeof AuthenticatedContentTypesIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/content-items/$id/edit': typeof AuthenticatedContentItemsIdEditRoute
  '/_authenticated/content-types/$name/edit': typeof AuthenticatedContentTypesNameEditRoute
  '/_authenticated/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/_authenticated/content-items/$id/': typeof AuthenticatedContentItemsIdIndexRoute
  '/_authenticated/content-types/$name/': typeof AuthenticatedContentTypesNameIndexRoute
  '/_authenticated/content-types/new/': typeof AuthenticatedContentTypesNewIndexRoute
  '/_authenticated/roles/$id/': typeof AuthenticatedRolesIdIndexRoute
  '/_authenticated/users/$id/': typeof AuthenticatedUsersIdIndexRoute
  '/_authenticated/content-types/$name/items/new': typeof AuthenticatedContentTypesNameItemsNewRoute
  '/_authenticated/content-types/$name/items/': typeof AuthenticatedContentTypesNameItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/login'
    | '/roles/new'
    | '/users/new'
    | '/content-items'
    | '/content-types'
    | '/roles'
    | '/users'
    | '/content-items/$id/edit'
    | '/content-types/$name/edit'
    | '/users/$id/edit'
    | '/content-items/$id'
    | '/content-types/$name'
    | '/content-types/new'
    | '/roles/$id'
    | '/users/$id'
    | '/content-types/$name/items/new'
    | '/content-types/$name/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/'
    | '/login'
    | '/roles/new'
    | '/users/new'
    | '/content-items'
    | '/content-types'
    | '/roles'
    | '/users'
    | '/content-items/$id/edit'
    | '/content-types/$name/edit'
    | '/users/$id/edit'
    | '/content-items/$id'
    | '/content-types/$name'
    | '/content-types/new'
    | '/roles/$id'
    | '/users/$id'
    | '/content-types/$name/items/new'
    | '/content-types/$name/items'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/'
    | '/login/'
    | '/_authenticated/roles/new'
    | '/_authenticated/users/new'
    | '/_authenticated/content-items/'
    | '/_authenticated/content-types/'
    | '/_authenticated/roles/'
    | '/_authenticated/users/'
    | '/_authenticated/content-items/$id/edit'
    | '/_authenticated/content-types/$name/edit'
    | '/_authenticated/users/$id/edit'
    | '/_authenticated/content-items/$id/'
    | '/_authenticated/content-types/$name/'
    | '/_authenticated/content-types/new/'
    | '/_authenticated/roles/$id/'
    | '/_authenticated/users/$id/'
    | '/_authenticated/content-types/$name/items/new'
    | '/_authenticated/content-types/$name/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-types/': {
      id: '/_authenticated/content-types/'
      path: '/content-types'
      fullPath: '/content-types'
      preLoaderRoute: typeof AuthenticatedContentTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-items/': {
      id: '/_authenticated/content-items/'
      path: '/content-items'
      fullPath: '/content-items'
      preLoaderRoute: typeof AuthenticatedContentItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/new': {
      id: '/_authenticated/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AuthenticatedRolesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id/': {
      id: '/_authenticated/users/$id/'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/$id/': {
      id: '/_authenticated/roles/$id/'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AuthenticatedRolesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-types/new/': {
      id: '/_authenticated/content-types/new/'
      path: '/content-types/new'
      fullPath: '/content-types/new'
      preLoaderRoute: typeof AuthenticatedContentTypesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-types/$name/': {
      id: '/_authenticated/content-types/$name/'
      path: '/content-types/$name'
      fullPath: '/content-types/$name'
      preLoaderRoute: typeof AuthenticatedContentTypesNameIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-items/$id/': {
      id: '/_authenticated/content-items/$id/'
      path: '/content-items/$id'
      fullPath: '/content-items/$id'
      preLoaderRoute: typeof AuthenticatedContentItemsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id/edit': {
      id: '/_authenticated/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthenticatedUsersIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-types/$name/edit': {
      id: '/_authenticated/content-types/$name/edit'
      path: '/content-types/$name/edit'
      fullPath: '/content-types/$name/edit'
      preLoaderRoute: typeof AuthenticatedContentTypesNameEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-items/$id/edit': {
      id: '/_authenticated/content-items/$id/edit'
      path: '/content-items/$id/edit'
      fullPath: '/content-items/$id/edit'
      preLoaderRoute: typeof AuthenticatedContentItemsIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-types/$name/items/': {
      id: '/_authenticated/content-types/$name/items/'
      path: '/content-types/$name/items'
      fullPath: '/content-types/$name/items'
      preLoaderRoute: typeof AuthenticatedContentTypesNameItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content-types/$name/items/new': {
      id: '/_authenticated/content-types/$name/items/new'
      path: '/content-types/$name/items/new'
      fullPath: '/content-types/$name/items/new'
      preLoaderRoute: typeof AuthenticatedContentTypesNameItemsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRolesNewRoute: typeof AuthenticatedRolesNewRoute
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedContentItemsIndexRoute: typeof AuthenticatedContentItemsIndexRoute
  AuthenticatedContentTypesIndexRoute: typeof AuthenticatedContentTypesIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedContentItemsIdEditRoute: typeof AuthenticatedContentItemsIdEditRoute
  AuthenticatedContentTypesNameEditRoute: typeof AuthenticatedContentTypesNameEditRoute
  AuthenticatedUsersIdEditRoute: typeof AuthenticatedUsersIdEditRoute
  AuthenticatedContentItemsIdIndexRoute: typeof AuthenticatedContentItemsIdIndexRoute
  AuthenticatedContentTypesNameIndexRoute: typeof AuthenticatedContentTypesNameIndexRoute
  AuthenticatedContentTypesNewIndexRoute: typeof AuthenticatedContentTypesNewIndexRoute
  AuthenticatedRolesIdIndexRoute: typeof AuthenticatedRolesIdIndexRoute
  AuthenticatedUsersIdIndexRoute: typeof AuthenticatedUsersIdIndexRoute
  AuthenticatedContentTypesNameItemsNewRoute: typeof AuthenticatedContentTypesNameItemsNewRoute
  AuthenticatedContentTypesNameItemsIndexRoute: typeof AuthenticatedContentTypesNameItemsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRolesNewRoute: AuthenticatedRolesNewRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedContentItemsIndexRoute: AuthenticatedContentItemsIndexRoute,
  AuthenticatedContentTypesIndexRoute: AuthenticatedContentTypesIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedContentItemsIdEditRoute: AuthenticatedContentItemsIdEditRoute,
  AuthenticatedContentTypesNameEditRoute:
    AuthenticatedContentTypesNameEditRoute,
  AuthenticatedUsersIdEditRoute: AuthenticatedUsersIdEditRoute,
  AuthenticatedContentItemsIdIndexRoute: AuthenticatedContentItemsIdIndexRoute,
  AuthenticatedContentTypesNameIndexRoute:
    AuthenticatedContentTypesNameIndexRoute,
  AuthenticatedContentTypesNewIndexRoute:
    AuthenticatedContentTypesNewIndexRoute,
  AuthenticatedRolesIdIndexRoute: AuthenticatedRolesIdIndexRoute,
  AuthenticatedUsersIdIndexRoute: AuthenticatedUsersIdIndexRoute,
  AuthenticatedContentTypesNameItemsNewRoute:
    AuthenticatedContentTypesNameItemsNewRoute,
  AuthenticatedContentTypesNameItemsIndexRoute:
    AuthenticatedContentTypesNameItemsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
