/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ContentTypesIndexRouteImport } from './routes/content-types/index'
import { Route as ContentItemsIndexRouteImport } from './routes/content-items/index'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as RolesNewRouteImport } from './routes/roles/new'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as UsersIdIndexRouteImport } from './routes/users/$id/index'
import { Route as RolesIdIndexRouteImport } from './routes/roles/$id/index'
import { Route as ContentTypesNewIndexRouteImport } from './routes/content-types/new/index'
import { Route as ContentTypesIdIndexRouteImport } from './routes/content-types/$id/index'
import { Route as ContentItemsIdIndexRouteImport } from './routes/content-items/$id/index'
import { Route as UsersIdEditRouteImport } from './routes/users/$id/edit'
import { Route as ContentItemsIdEditRouteImport } from './routes/content-items/$id/edit'
import { Route as ContentTypesIdItemsIndexRouteImport } from './routes/content-types/$id/items/index'
import { Route as ContentTypesIdItemsNewRouteImport } from './routes/content-types/$id/items/new'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypesIndexRoute = ContentTypesIndexRouteImport.update({
  id: '/content-types/',
  path: '/content-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentItemsIndexRoute = ContentItemsIndexRouteImport.update({
  id: '/content-items/',
  path: '/content-items/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesNewRoute = RolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UsersIdIndexRoute = UsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIdIndexRoute = RolesIdIndexRouteImport.update({
  id: '/roles/$id/',
  path: '/roles/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypesNewIndexRoute = ContentTypesNewIndexRouteImport.update({
  id: '/content-types/new/',
  path: '/content-types/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypesIdIndexRoute = ContentTypesIdIndexRouteImport.update({
  id: '/content-types/$id/',
  path: '/content-types/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentItemsIdIndexRoute = ContentItemsIdIndexRouteImport.update({
  id: '/content-items/$id/',
  path: '/content-items/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdEditRoute = UsersIdEditRouteImport.update({
  id: '/users/$id/edit',
  path: '/users/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentItemsIdEditRoute = ContentItemsIdEditRouteImport.update({
  id: '/content-items/$id/edit',
  path: '/content-items/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypesIdItemsIndexRoute =
  ContentTypesIdItemsIndexRouteImport.update({
    id: '/content-types/$id/items/',
    path: '/content-types/$id/items/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContentTypesIdItemsNewRoute = ContentTypesIdItemsNewRouteImport.update({
  id: '/content-types/$id/items/new',
  path: '/content-types/$id/items/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/content-items': typeof ContentItemsIndexRoute
  '/content-types': typeof ContentTypesIndexRoute
  '/login': typeof LoginIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/content-items/$id/edit': typeof ContentItemsIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/content-items/$id': typeof ContentItemsIdIndexRoute
  '/content-types/$id': typeof ContentTypesIdIndexRoute
  '/content-types/new': typeof ContentTypesNewIndexRoute
  '/roles/$id': typeof RolesIdIndexRoute
  '/users/$id': typeof UsersIdIndexRoute
  '/content-types/$id/items/new': typeof ContentTypesIdItemsNewRoute
  '/content-types/$id/items': typeof ContentTypesIdItemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/content-items': typeof ContentItemsIndexRoute
  '/content-types': typeof ContentTypesIndexRoute
  '/login': typeof LoginIndexRoute
  '/roles': typeof RolesIndexRoute
  '/users': typeof UsersIndexRoute
  '/content-items/$id/edit': typeof ContentItemsIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/content-items/$id': typeof ContentItemsIdIndexRoute
  '/content-types/$id': typeof ContentTypesIdIndexRoute
  '/content-types/new': typeof ContentTypesNewIndexRoute
  '/roles/$id': typeof RolesIdIndexRoute
  '/users/$id': typeof UsersIdIndexRoute
  '/content-types/$id/items/new': typeof ContentTypesIdItemsNewRoute
  '/content-types/$id/items': typeof ContentTypesIdItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/roles/new': typeof RolesNewRoute
  '/users/new': typeof UsersNewRoute
  '/content-items/': typeof ContentItemsIndexRoute
  '/content-types/': typeof ContentTypesIndexRoute
  '/login/': typeof LoginIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/content-items/$id/edit': typeof ContentItemsIdEditRoute
  '/users/$id/edit': typeof UsersIdEditRoute
  '/content-items/$id/': typeof ContentItemsIdIndexRoute
  '/content-types/$id/': typeof ContentTypesIdIndexRoute
  '/content-types/new/': typeof ContentTypesNewIndexRoute
  '/roles/$id/': typeof RolesIdIndexRoute
  '/users/$id/': typeof UsersIdIndexRoute
  '/content-types/$id/items/new': typeof ContentTypesIdItemsNewRoute
  '/content-types/$id/items/': typeof ContentTypesIdItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/roles/new'
    | '/users/new'
    | '/content-items'
    | '/content-types'
    | '/login'
    | '/roles'
    | '/users'
    | '/content-items/$id/edit'
    | '/users/$id/edit'
    | '/content-items/$id'
    | '/content-types/$id'
    | '/content-types/new'
    | '/roles/$id'
    | '/users/$id'
    | '/content-types/$id/items/new'
    | '/content-types/$id/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/roles/new'
    | '/users/new'
    | '/content-items'
    | '/content-types'
    | '/login'
    | '/roles'
    | '/users'
    | '/content-items/$id/edit'
    | '/users/$id/edit'
    | '/content-items/$id'
    | '/content-types/$id'
    | '/content-types/new'
    | '/roles/$id'
    | '/users/$id'
    | '/content-types/$id/items/new'
    | '/content-types/$id/items'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/roles/new'
    | '/users/new'
    | '/content-items/'
    | '/content-types/'
    | '/login/'
    | '/roles/'
    | '/users/'
    | '/content-items/$id/edit'
    | '/users/$id/edit'
    | '/content-items/$id/'
    | '/content-types/$id/'
    | '/content-types/new/'
    | '/roles/$id/'
    | '/users/$id/'
    | '/content-types/$id/items/new'
    | '/content-types/$id/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RolesNewRoute: typeof RolesNewRoute
  UsersNewRoute: typeof UsersNewRoute
  ContentItemsIndexRoute: typeof ContentItemsIndexRoute
  ContentTypesIndexRoute: typeof ContentTypesIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ContentItemsIdEditRoute: typeof ContentItemsIdEditRoute
  UsersIdEditRoute: typeof UsersIdEditRoute
  ContentItemsIdIndexRoute: typeof ContentItemsIdIndexRoute
  ContentTypesIdIndexRoute: typeof ContentTypesIdIndexRoute
  ContentTypesNewIndexRoute: typeof ContentTypesNewIndexRoute
  RolesIdIndexRoute: typeof RolesIdIndexRoute
  UsersIdIndexRoute: typeof UsersIdIndexRoute
  ContentTypesIdItemsNewRoute: typeof ContentTypesIdItemsNewRoute
  ContentTypesIdItemsIndexRoute: typeof ContentTypesIdItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-types/': {
      id: '/content-types/'
      path: '/content-types'
      fullPath: '/content-types'
      preLoaderRoute: typeof ContentTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-items/': {
      id: '/content-items/'
      path: '/content-items'
      fullPath: '/content-items'
      preLoaderRoute: typeof ContentItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/new': {
      id: '/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof RolesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/users/$id/': {
      id: '/users/$id/'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/$id/': {
      id: '/roles/$id/'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof RolesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-types/new/': {
      id: '/content-types/new/'
      path: '/content-types/new'
      fullPath: '/content-types/new'
      preLoaderRoute: typeof ContentTypesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-types/$id/': {
      id: '/content-types/$id/'
      path: '/content-types/$id'
      fullPath: '/content-types/$id'
      preLoaderRoute: typeof ContentTypesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-items/$id/': {
      id: '/content-items/$id/'
      path: '/content-items/$id'
      fullPath: '/content-items/$id'
      preLoaderRoute: typeof ContentItemsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id/edit': {
      id: '/users/$id/edit'
      path: '/users/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof UsersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-items/$id/edit': {
      id: '/content-items/$id/edit'
      path: '/content-items/$id/edit'
      fullPath: '/content-items/$id/edit'
      preLoaderRoute: typeof ContentItemsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-types/$id/items/': {
      id: '/content-types/$id/items/'
      path: '/content-types/$id/items'
      fullPath: '/content-types/$id/items'
      preLoaderRoute: typeof ContentTypesIdItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-types/$id/items/new': {
      id: '/content-types/$id/items/new'
      path: '/content-types/$id/items/new'
      fullPath: '/content-types/$id/items/new'
      preLoaderRoute: typeof ContentTypesIdItemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RolesNewRoute: RolesNewRoute,
  UsersNewRoute: UsersNewRoute,
  ContentItemsIndexRoute: ContentItemsIndexRoute,
  ContentTypesIndexRoute: ContentTypesIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ContentItemsIdEditRoute: ContentItemsIdEditRoute,
  UsersIdEditRoute: UsersIdEditRoute,
  ContentItemsIdIndexRoute: ContentItemsIdIndexRoute,
  ContentTypesIdIndexRoute: ContentTypesIdIndexRoute,
  ContentTypesNewIndexRoute: ContentTypesNewIndexRoute,
  RolesIdIndexRoute: RolesIdIndexRoute,
  UsersIdIndexRoute: UsersIdIndexRoute,
  ContentTypesIdItemsNewRoute: ContentTypesIdItemsNewRoute,
  ContentTypesIdItemsIndexRoute: ContentTypesIdItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
